services:
  node:
    image: node:lts-slim
    working_dir: /src
    env_file:
      - .env
    command: /bin/sh -c "npm install nodemailer && npm install && npm audit fix --force && npx nodemon src/app.js"
    ports:
      - '32543:3000'
    volumes:
      - ./src:/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:lts
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '127.0.0.1:8081:80'
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1

volumes:
  mariadb_data:
