services:
  node:
    image: node:lts-slim
    working_dir: /src
    env_file:
      - .env
    command: /bin/sh -c "apt update && apt install -y curl &&npm install nodemailer && npm install && npm audit fix --force && npm start"
    volumes:
      - ./src:/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://node:3000/kits"]
        interval: 30s
        timeout: 10s
        retries: 5

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-conf/proxy_params:/etc/nginx/proxy_params
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - node
    networks:
      - app-network

  db:
    image: mariadb:lts
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '127.0.0.1:8081:80'
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1
    networks:
      - app-network

  unit-test:
    image: node:lts-slim
    working_dir: /src
    environment:
      - NODE_ENV=test
    command: /bin/sh -c "npm install --save-dev jest && npm install && npm run test:unit"
    volumes:
      - ./src:/src
    networks:
      - app-network
    profiles:
      - unit-test

  integration-test:
    image: node:lts-slim
    working_dir: /src
    environment:
      - NODE_ENV=test
      - API_URL=http://node:3000
      - npm_config_audit_level=moderate
    command: /bin/sh -c "npm install --save-dev jest supertest --silent && npm install --silent && npm run test:integration"
    volumes:
      - ./src:/src
    depends_on:
      db:
        condition: service_healthy
      node:
        condition: service_healthy
    networks:
      - app-network
    profiles:
      - integration-test


volumes:
  mariadb_data:

networks:
  app-network:
